### ISSUE TITLE
public_internet_gateway aws_routes do not destroy cleanly

### ISSUE THREAD

**Issue by tjtaill** [gnokoheat/ecs-with-codepipeline-example-by-terraform#2]
Hi your code has been really helpful to me so I want to thank you it works really well for apply. But when I try to destroy there are errors "Error deleting route: InvalidRoute.NotFound: no route with destination-cidr-block 0.0.0.0/0 in route table rtb-0bda47a18903a536c
        status code: 400, request id: f7229d03-123b-4f60-891d-c92c11593678"

when it tries to delete the second public_internet_gateway aws_route the resource is here in the code https://github.com/gnokoheat/ecs-with-codepipeline-example-by-terraform/blob/master/vpc.tf#L67

I have tried a lot of different things mostly in changing depends_on but nothing has worked

seems related to this https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/373

**Comment by gnokoheat** [comment]
@tjtaill hello😊 I hope to help you with my code.
well, I never been have same issue even use same code.
This code is just example code for who want to understand to aws ecs with codepipeline.
So, I don't define detail like `depend_on` options with resources.
Also, I've been applying terraform to many infra works.
I guess almost these issue is because of the sync.
First, check your terraform state with aws resource in directly.
If you find something, should edit terraform state manually.
